import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { PrimaryLinkButtonStyle } from "~/component/PrimaryLinkButtonStyle";

function HeroBanner() {
  return (
    <section className="mb-24 mt-12 grid grid-cols-1 gap-12 px-8 sm:mt-24 sm:grid-cols-2">
      <div className="flex flex-col gap-10">
        <h1 className="text-4xl font-bold sm:text-6xl">
          Generate icons with a click of a button
        </h1>
        <p className="text-xl sm:text-2xl">
          Use AI to generate icons in seconds instead of paying a designer and
          waiting for them to create them for you.
        </p>
        <PrimaryLinkButtonStyle href="/generate" className="self-start">
          Generate your Icons
        </PrimaryLinkButtonStyle>
      </div>
      <Image
        src="/undraw_icons_wdp4.svg"
        alt="An image depicting two people designing icons"
        height="500"
        width="500"
        className="order-first self-center sm:order-none"
      />
    </section>
  );
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Icon Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col">
        <HeroBanner />
      </main>
    </>
  );
};

export default Home;
